bazelbuild/rules_appengine

- appengine/appengine.bzl
These aren't actually used. I think these used to be runtime dependencies
of dash, which made me think they were required for AppEngine rules, but
they are not.
> Remove Apache dependencies

- test/BUILD
- test/check_war.sh
Just makes sure it's creating a war with the right contents. This will
let `bazel test //...` run on ci.bazel.io.
> Add a basic test

- README.md
- appengine/appengine.bzl
This is a prereq for removing appengine rules from @bazel_tools.
> Remove reference to @bazel_tools

- test/BUILD
- test/check_war.sh
Also use jar from local_jdk instead of relying on it on the PATH
Fix build with bazel @HEAD
> Fix runfiles path in check_war test

- appengine/appengine.bzl
- appengine/appengine_runner.sh.template
This fixes the appengine rules to work when the workspace name is set.
This finishes fixing https://github.com/bazelbuild/bazel/issues/1233.
CC @pmbethe09.
> Add workspace name to runfiles path

- appengine/appengine.bzl
This makes it easier to sub in a local copy of the app engine SDK (note
the version is different):
```
load("//appengine:appengine.bzl", "APPENGINE_BUILD_FILE")
new_local_repository(
name = "com_google_appengine_java",
path = “/path/to/a/local/appengine-java-sdk-1.9.34",
build_file_content = APPENGINE_BUILD_FILE,
)
```
> Strip the AppEngine dir prefix

- README.md
- appengine/appengine.bzl
Okay, ditched the strip prefix (it made the symlinking inconvenient) but I think this should be a nice option for most developers.
> Pick up a local SDK from an environment variable

- appengine/appengine.bzl
- appengine/appengine_runner.sh.template
Previously, these rules were zipping up a .war and then, when the
executable ran, it would make a temporary directory and unzip the war
there. It is faster to develop just using the runfiles tree.
This commit also makes several other changes (that I can split out if
you prefer):
* Doesn’t include every jar in the app engine sdk in the build (only
the ones that, AFAICT, you actually need).
* Fails fast if the app engine sdk glob didn’t return anything (which
happens to me a lot when I use a local_repo for
com_google_appengine_java because I always forget it expects an
APPENGINE_DIR subdirectory).
* Uses .format for python string replacement
> Run dev app server directly from runfiles tree

- appengine/appengine.bzl
- appengine/appengine_runner.sh.template
- examples/BUILD
- examples/src/App.java
- examples/src/BUILD
- examples/webapp/BUILD
- examples/webapp/WEB-INF/appengine-web.xml
- examples/webapp/WEB-INF/web.xml
This reverts commit 404c74f5687a3df1ad585219dac3bd371ab5f450.
Reverts the change I made to the :api target, although I removed the hundreds of jars from the classpath. Previously the bazel rule would add appengine-sdk/lib/**/*.jar to the CLASSPATH. You can still include these jars by depending on //:jars from your whatever_deploy.jar rule.
> Un-revert "Run dev app server directly from runfiles tree (#24)"

- .idea/vcs.xml
- README.md
- appengine/appengine.bzl
- appengine/appengine_deploy.sh.template
Issue #31 (zipper: no such file directory) is caused by an unresolved dependency.
When the user invokes `blaze run //foo/bar/gae:gae.deploy`, the target is only a `ctx.template_action`, i.e. Bazel generates the deploy script, but has no reason to actually build the war (nor resolve the zipper dependency).
The only reson why `blaze run //foo/bar/gae:gae` successfully starts a local server is because the launcher script has the same name as the `appengine_war` rule.
To work around this issue, I'm adding a bazel macro that defines a `sh_binary` which depends on the war. Essentially:
def appengine(name, jars, data, data_path):
appengine_war(name = name,
jars = jars,
data = data,
data_path = data_path)
native.sh_binary(name = "%s.deploy" % name,
srcs = ["%s_deploy.sh" % name],
data = [name]) …
> Make the .deploy rule resolve the dependencies

- README.md
- appengine/appengine.bzl
- appengine/appengine_deploy.sh.template
Reverts bazelbuild/rules_appengine#32
This breaks our CI (http://ci.bazel.io/view/Dashboard/job/rules_appengine/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/lastFailedBuild/console) because it is now a macro which doesn't understand "testonly".  Should be a simple fix, but rolling back for now to keep the CI green.
> Revert "Make the .deploy rule resolve the dependencies"

- appengine/appengine_runner.sh.template
I guess AppEngine got stricter about this. As AppEngine's help says, it's
Usage: <dev-appserver> [options] <app directory>
We were trying to do:
<dev-appserver> [some options] <app directory> [more options]
> Give path to webapp as the last argument

- appengine/BUILD
Bazel's commit 202d5910a194ae5a0dfbc11692a17e8013017aca changes how singlejar is referenced, change to update.
> Fix reference to singlejar

- appengine/py_appengine.bzl
Previously, there was no way of deploying the non-main module.
> Add py_appengine support for deploying multiple modules.

- appengine/appengine.bzl
Currently the creation of a war file fails when it contains too many
files with the error 'Argument list too long'. This is fixed by creating
a file with the list of input files.
> Support creating war files with many files

- .bazelci/presubmit.yml
- README.md
Bazel is moving to a new CI system and we would like to test every commit to rules_appengine to make sure a new release doesn't break it.
> add bazel CI configuration

- appengine/py/appengine_runner.sh.template
The [Java runner](https://github.com/bazelbuild/rules_appengine/blob/master/appengine/java/appengine_runner.sh.template) does this, so Python should too.
> Pass extra CLI parameters to dev_appserver

- README.md
I was getting the same error as reported in #63. This was fixed for me by adding a "/' to the data_path, just like the examples folder rule does.
> Fixing data_path on README to avoid #63

- test/java/BUILD
- test/java/check_war.sh
instead of `@local_jdk//:jdk-default`, which is going away in a future
Bazel release.
> Use the standard idiom for accessing the JDK

- appengine/java_appengine.bzl
Collect transitive runtime deps using `JavaInfo` provider (this will support any target providing `JavaInfo` such as `scala_import` and `scala_library`)
> Collect transitive runtime deps from JavaInfo

- appengine/BUILD
UTF-8 is the only supported option.
> Remove 'encoding' attribute from java_toolchain.

- appengine/java_appengine.bzl
- test/java/check_war.sh
Use package name to create a "full" target name, hence, supporting targets with the same name originating from different packages
> Use full target names

- WORKSPACE
Adds the appengine_repositories() rule to the WORKSPACE which was added 8122a70. This rule is now  required for the python rules (and will be for the java rules once I update them).
Fixes https://github.com/bazelbuild/rules_appengine/issues/87
> Fixes CI caused by missing appengine_repositories()

- appengine/py_appengine.bzl
Currently, when the user specifies an `appengine_config.py` file, the rule patches it into a base config. This PR adds a new option, `dont_overwrite_appengine_config`, that disables the patching behavior and instead uses the user's config directly. When `dont_overwrite_appengine_config` is False, the old behavior is unchanged.
> Python: Add option to not overwrite the appengine_config.py

- appengine/py/appengine_deploy.sh.template
- appengine/py_appengine.bzl
'gcloud app deploy' does not deploy cron.yaml/index.yaml/dispatch.yaml by default.
It does make sense to deploy all yaml configs listed for build target by default.
> propagate yaml configs to gcloud during deployment

- appengine/java_appengine.bzl
- appengine/py_appengine.bzl
In particular, remove string itertion, FileType, and single_file
Tested:
`bazel-0.21 test //... --all_incompatible_changes --incompatible_depset_union=false --incompatible_depset_is_not_iterable=false --incompatible_new_actions_api=false`
> Remove deprecated Bazel features

- appengine/py_appengine.bzl
This incompatible change flag, and the PyInfo provider it requires, were introduced in Bazel 0.23. The incompatible change may be enabled as soon as Bazel 0.25.
> Small fix to build with --incompatible_disallow_legacy_py_provider

- appengine/py/sdk.BUILD
The glob pattern "lib/six/**/*.py" didn't match anything, so the library
was empty. Non-matching globs will be forbidden in Bazel (see flag
--incompatible_disallow_empty_glob).
> Remove library six from the BUILD file

- appengine/java/appengine_runner.sh.template
- appengine/java_appengine.bzl
With the attribute user can specify the JVM arguments in BUILD file. These arguments are passed to JVM when the target is executed.
More context in https://github.com/bazelbuild/rules_appengine/issues/109
> Support local_jvm_flags attribute in java_war and appengine_war

- appengine/BUILD
The implementation of java_toolchain already does nothing with the extclasspath value. The attribute has been removed.
javac is handled the same way if added to tools attribute.
> Remove extclasspath and put javac into tools attribute.

- README.md
- appengine/BUILD
- appengine/java_appengine.bzl
I replaced direct use of "java_toolchain" rule with "default_java_toolchain" macro, which already has some good defaults and it exists in Bazel for quite some time. Macro is easier to maintain, because the defaults can be changed within Bazel.
Newer Bazel (>4.0.0) is changing how Java toolchains are resolved. I updated the README.md accordingly. In newer version of Bazel it is easier to use the macro, because it also adds necessary toolchain definitions.
Newer Bazel also has presets for JVM8 configuration which I used in "default_java_toolchain". The preset in newer version is needed, because it will ensure code is compiled on JDK8 for JVM8. Without it the code is compiled on JDK11 for JVM8.
The whole commit is a bit complicated, but I don't know an easier way how to have rules_appengine …
> Setup JDK8 toolchain depending on the Bazel version.

- README.md
- WORKSPACE
- appengine/java_appengine.bzl
I imported bazel-skylib and used version check from there.
Fixes https://github.com/bazelbuild/rules_appengine/issues/122
> Use bazel-skylib for a proper version check.

- README.md
- WORKSPACE
This enables rules_appengine to work on machines, that don't have
JDK 8 installed.
Fixes https://github.com/bazelbuild/rules_appengine/issues/119
> Import JDK8 from remote repository and add instructions.

- appengine/java_appengine.bzl
Java platformization will happen with 5.0.0 instead of 4.1.0
> Fix Bazel version that will enable Java platformization
